# srcs/docker-compose.yml

services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    image: nginx_inception
    ports:
      - "443:443" 
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - inception_network
    depends_on:
      - wordpress
    env_file: .env
    restart: always

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    image: wordpress_inception
    volumes:
      - wordpress_files:/var/www/html
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - inception_network
    restart: always

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    image: mariadb_inception
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file: .env
    networks:
      - inception_network
    restart: always

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/fvastena/data/mariadb
  wordpress_files:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/fvastena/data/wordpress


networks:
  inception_network:
    driver: bridge