# ~/inception/srcs/docker-compose.yml
version: '3.8' # Use a recent version

# Define the custom network
networks:
  inception_network:
    driver: bridge

# Define the volumes for persistent data
volumes:
  wordpress_data:
    driver: local
  mariadb_data:
    driver: local

# Services will be defined here later
services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network
    env_file: 
      - .env
    environment:
      MYSQL_DATABASE: wordpress
    restart: always
    secrets:
      - mysql_password
      - mysql_root_password

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception_network
    restart: always
    env_file:
      - .env # To get DOMAIN_NAME, WP_USER
    environment:
      MYSQL_DATABASE: wordpress # Or use an env var from .env
      WP_EMAIL: user@${DOMAIN_NAME} # Example email
    secrets:
      - mysql_password # Used by wp-config.sh
      - wp_admin_user
      - wp_admin_password
      - wp_password # Password for the second user

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
      args: # Pass build arguments
        - DOMAIN_NAME=${DOMAIN_NAME}
    container_name: nginx
    ports:
      - "443:443" # Map host port 443 to container port 443
    networks:
      - inception_network
    restart: always
    env_file:
      - .env # To get DOMAIN_NAME
    depends_on:
      - wordpress # Ensure WordPress is running before NGINX starts
    
# Secrets will be defined here later
  mysql_password:
    file: ./secrets/db_password.txt
  mysql_root_password:
    file: ./secrets/db_root_password.txt
  wp_admin_password:
    file: ./secrets/wp_admin_password.txt # Assuming admin password is in credentials.txt
  wp_password:
    file: ./secrets/wp_password.txt # Assuming second user password is in credentials.txt
